version: '3.8'
services:
  vprodb: 
    build: ./Docker-files/db
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql

  vprocache01:
    image: memcached
    ports: 
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: ./Docker-files/app
    ports:
      - "9000:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  
  vproweb:
    build: ./Docker-files/nginx
    ports:
      - "80:80"
  
volumes:
  vprodbdata: {}
  vproappdata: {}
  